{% set name = "types-atomicwrites" %}
{% set version = "1.4.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types-atomicwrites-{{ version }}.tar.gz
  sha256: 9e9f0923ebf93524b28bcece5a23ac8c3820f39b060df29f671936d2e4bc04bc

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f $SP_DIR/atomicwrites-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for atomicwrites
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
