{% set name = "types-atomicwrites" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-atomicwrites-{{ version }}.tar.gz
  sha256: a5bfba4d98a352424a7c8a71fbe2109970245d0253bd0efe9f2ed930a011d817

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/atomicwrites-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for atomicwrites
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
